language: python
python:
  - "2.7"

before_install:
  - sudo apt-get install -qq python openssl git python-qt4

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - python bitmessage/install.py

# command to run tests, e.g. python setup.py test
script:
  - python -m unittest discover unittests
